package card

import (
	"github.com/asukakenji/clash-royale/arena"
	"github.com/asukakenji/clash-royale/attr"
	"github.com/asukakenji/clash-royale/common"
	"github.com/asukakenji/clash-royale/rarity"
	"github.com/asukakenji/clash-royale/rng"
	"github.com/asukakenji/clash-royale/speed"
	"github.com/asukakenji/clash-royale/targets"
	"github.com/asukakenji/clash-royale/typ"
)

var cards20160104 = [...]card{
	// --- Common Troops ---
	card{
		attr.Name:    "Knight",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `A tough melee fighter. The Barbarian's handsome, cultured cousin. Rumor has it that he was knighted based on the sheer awesomeness of his mustache alone.`,
		attr.Elixir:  3,
		attr.BaseHP:  660,
		attr.DPS:     []interface{}{68, 74, 81, 90, 99, 109, 120, 130, 144, 158, 174, 190, 210},
		attr.BaseDam: 75,
		attr.HSpeed:  1.1,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Medium,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:    "Archers",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `A pair of lightly armored ranged attackers. They'll help you take down ground and air units, but you're on your own with hair coloring advice.`,
		attr.Elixir:  3,
		attr.BaseHP:  120,
		attr.DPS:     []interface{}{34, 37, 40, 45, 49, 54, 60, 65, 71, 79, 86, 95, 105},
		attr.BaseDam: 41,
		attr.HSpeed:  1.2,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.Medium,
		attr.Range:   5,
		attr.DTime:   1,
		attr.Count:   2,
	}.init(),
	card{
		attr.Name:     "Bomber",
		attr.Arena:    arena.Arena0,
		attr.Rarity:   rarity.Common,
		attr.Type:     typ.Troop,
		attr.Desc:     `Small, lightly protected skeleton that throws bombs. Deals area damage that can wipe out a swarm of enemies.`,
		attr.Elixir:   3,
		attr.BaseHP:   147,
		attr.DPS:      []interface{}{67, 73, 81, 89, 97, 107, 118, 130, 142, 156, 172, 188, 207},
		attr.BaseADam: 128,
		attr.HSpeed:   1.9,
		attr.Targets:  targets.Ground,
		attr.Speed:    speed.Medium,
		attr.Range:    4.5,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:    "Goblins",
		attr.Arena:   arena.Arena1,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `Three fast, unarmored melee attackers. Small, fast, green and mean!`,
		attr.Elixir:  2,
		attr.BaseHP:  80,
		attr.DPS:     []interface{}{45, 50, 54, 60, 66, 72, 80, 87, 96, 105, 116, 127, 140},
		attr.BaseDam: 50,
		attr.HSpeed:  1.1,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.VeryFast,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
		attr.Count:   3,
	}.init(),
	card{
		attr.Name:    "Spear Goblins",
		attr.Arena:   arena.Arena1,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `Three unarmored ranged attackers. Who the heck taught these guys to throw spears!?! Who thought that was a good idea?!`,
		attr.Elixir:  2,
		attr.BaseHP:  52,
		attr.DPS:     []interface{}{18, 20, 22, 23, 26, 29, 32, 35, 38, 42, 46, 51, 56},
		attr.BaseDam: 24,
		attr.HSpeed:  1.3,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.VeryFast,
		attr.Range:   5,
		attr.DTime:   1,
		attr.Count:   3,
	}.init(),
	card{
		attr.Name:    "Skeletons",
		attr.Arena:   arena.Arena2,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `Three fast, very weak melee fighters. Surround your enemies with this pile of bones!`,
		attr.Elixir:  1,
		attr.BaseHP:  32,
		attr.DPS:     []interface{}{32, 35, 38, 42, 46, 51, 56, 61, 67, 74, 81, 89, 98},
		attr.BaseDam: 32,
		attr.HSpeed:  1,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Fast,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
		attr.Count:   3,
	}.init(),
	card{
		attr.Name:    "Minions",
		attr.Arena:   arena.Arena2,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `Three fast, unarmored flying attackers. Roses are red, minions are blue, they can fly, and will crush you!`,
		attr.Elixir:  3,
		attr.BaseHP:  90,
		attr.DPS:     []interface{}{40, 44, 48, 53, 58, 64, 70, 77, 84, 93, 102, 112, 123},
		attr.BaseDam: 40,
		attr.HSpeed:  1,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.Fast,
		attr.Range:   2,
		attr.DTime:   1,
		attr.Count:   3,
	}.init(),
	card{
		attr.Name:    "Barbarians",
		attr.Arena:   arena.Arena3,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `A horde of melee attackers with mean mustaches and even meaner tempers.`,
		attr.Elixir:  5,
		attr.BaseHP:  300,
		attr.DPS:     []interface{}{50, 54, 60, 66, 72, 80, 88, 96, 106, 116, 128, 140, 154},
		attr.BaseDam: 75,
		attr.HSpeed:  1.5,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Medium,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
		attr.Count:   4,
	}.init(),
	card{
		attr.Name:    "Minion Horde",
		attr.Arena:   arena.Arena4,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Troop,
		attr.Desc:    `Six fast, unarmored flying attackers. Three's a crowd, six is a horde!`,
		attr.Elixir:  5,
		attr.BaseHP:  90,
		attr.DPS:     []interface{}{40, 44, 48, 53, 58, 64, 70, 77, 84, 93, 102, 112, 123},
		attr.BaseDam: 40,
		attr.HSpeed:  1,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.Fast,
		attr.Range:   2,
		attr.DTime:   1,
		attr.Count:   6,
	}.init(),

	// --- Rare Troops ---
	card{
		attr.Name:    "Giant",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Rare,
		attr.Type:    typ.Troop,
		attr.Desc:    `Slow but durable, only attacks buildings. A real one-man wrecking crew!`,
		attr.Elixir:  5,
		attr.BaseHP:  1900,
		attr.DPS:     []interface{}{80, 88, 96, 106, 116, 128, 140, 154, 169, 186, 204},
		attr.BaseDam: 120,
		attr.HSpeed:  1.5,
		attr.Targets: targets.Buildings,
		attr.Speed:   speed.Slow,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:    "Musketeer",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Rare,
		attr.Type:    typ.Troop,
		attr.Desc:    `Don't be fooled by her delicately coiffed hair, the Musketeer is a mean shot with her trusty boomstick.`,
		attr.Elixir:  4,
		attr.BaseHP:  340,
		attr.DPS:     []interface{}{90, 100, 110, 120, 132, 145, 160, 175, 192, 211, 232},
		attr.BaseDam: 100,
		attr.HSpeed:  1.1,
		attr.Targets: targets.AirAndGround,
		attr.Speed:   speed.Medium,
		attr.Range:   6,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:    "Mini P.E.K.K.A",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Rare,
		attr.Type:    typ.Troop,
		attr.Desc:    `The Arena is a certified butterfly-free zone. No distractions for P.E.K.K.A, only destruction.`,
		attr.Elixir:  4,
		attr.BaseHP:  600,
		attr.DPS:     []interface{}{180, 198, 218, 240, 263, 288, 317, 348, 382, 420, 462},
		attr.BaseDam: 325,
		attr.HSpeed:  1.8,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Fast,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:     "Valkyrie",
		attr.Arena:    arena.Arena1,
		attr.Rarity:   rarity.Rare,
		attr.Type:     typ.Troop,
		attr.Desc:     `Tough melee fighter, deals area damage around her. Swarm or horde, no problem! She can take them all out with a few spins.`,
		attr.Elixir:   4,
		attr.BaseHP:   880,
		attr.DPS:      []interface{}{80, 88, 96, 106, 116, 128, 140, 154, 169, 186, 204},
		attr.BaseADam: 120,
		attr.HSpeed:   1.5,
		attr.Targets:  targets.Ground,
		attr.Speed:    speed.Medium,
		attr.Range:    rng.Melee,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:    "Hog Rider",
		attr.Arena:   arena.Arena4,
		attr.Rarity:  rarity.Rare,
		attr.Type:    typ.Troop,
		attr.Desc:    `Fast melee troop that targets buildings and can jump over the river. He followed the echoing call of "Hog Riderrrrr" all the way through the arena doors.`,
		attr.Elixir:  4,
		attr.BaseHP:  800,
		attr.DPS:     []interface{}{100, 110, 120, 132, 146, 160, 176, 192, 212, 232, 256},
		attr.BaseDam: 150,
		attr.HSpeed:  1.5,
		attr.Targets: targets.Buildings,
		attr.Speed:   speed.VeryFast,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:     "Wizard",
		attr.Arena:    arena.Arena5,
		attr.Rarity:   rarity.Rare,
		attr.Type:     typ.Troop,
		attr.Desc:     `The most awesome man to ever set foot in the arena, the Wizard will blow you away with his handsomeness... and/or fireballs.`,
		attr.Elixir:   5,
		attr.BaseHP:   340,
		attr.DPS:      []interface{}{92, 102, 112, 122, 135, 148, 162, 178, 196, 215, 237},
		attr.BaseADam: 130,
		attr.HSpeed:   1.4,
		attr.Targets:  targets.AirAndGround,
		attr.Speed:    speed.Medium,
		attr.Range:    5.5,
		attr.DTime:    1,
	}.init(),

	// --- Epic Troops ---
	card{
		attr.Name:      "Witch",
		attr.Arena:     arena.Arena0,
		attr.Rarity:    rarity.Epic,
		attr.Type:      typ.Troop,
		attr.Desc:      `Summons Skeletons, shoots destructo beams, has glowing pink eyes that unfortunately don't shoot lasers.`,
		attr.Elixir:    5,
		attr.BaseHP:    524,
		attr.DPS:       []interface{}{74, 81, 88, 98, 107, 118, 130, 142},
		attr.BaseADam:  52,
		attr.BaseSkeLV: 6,
		attr.SSpeed:    7,
		attr.HSpeed:    0.7,
		attr.Targets:   targets.AirAndGround,
		attr.Speed:     speed.Medium,
		attr.Range:     5,
		attr.DTime:     1,
	}.init(),
	card{
		attr.Name:      "Skeleton Army",
		attr.Arena:     arena.Arena0,
		attr.Rarity:    rarity.Epic,
		attr.Type:      typ.Troop,
		attr.Desc:      `Summons an army of Skeletons. Meet Larry and his friends Harry, Gerry, Terry, Mary, etc.`,
		attr.Elixir:    3,
		attr.BaseHP:    32,                                            // NOTE: Not shown in game anymore
		attr.DPS:       []interface{}{32, 35, 38, 42, 46, 51, 56, 61}, // NOTE: Not shown in game anymore
		attr.BaseDam:   32,                                            // NOTE: Not shown in game anymore
		attr.BaseSkeLV: 1,
		attr.HSpeed:    1,              // NOTE: Not shown in game anymore
		attr.Targets:   targets.Ground, // NOTE: Not shown in game anymore
		attr.Speed:     speed.Fast,     // NOTE: Not shown in game anymore
		attr.Range:     rng.Melee,      // NOTE: Not shown in game anymore
		attr.DTime:     1,
		attr.Count:     14,
	}.init(),
	card{
		attr.Name:     "Baby Dragon",
		attr.Arena:    arena.Arena0,
		attr.Rarity:   rarity.Epic,
		attr.Type:     typ.Troop,
		attr.Desc:     `Flying troop that deals area damage. Baby dragons hatch cute, hungry and ready for a barbeque.`,
		attr.Elixir:   4,
		attr.BaseHP:   800,
		attr.DPS:      []interface{}{62, 68, 75, 83, 91, 100, 110, 120},
		attr.BaseADam: 100,
		attr.HSpeed:   1.6,
		attr.Targets:  targets.AirAndGround,
		attr.Speed:    speed.Fast,
		attr.Range:    3.5,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:    "Prince",
		attr.Arena:   arena.Arena0,
		attr.Rarity:  rarity.Epic,
		attr.Type:    typ.Troop,
		attr.Desc:    `Don't let the little pony fool you. Once the Prince gets a running start, you WILL be trampled. Deals double damage once he gets charging.`,
		attr.Elixir:  5,
		attr.BaseHP:  1100,
		attr.DPS:     []interface{}{163, 179, 197, 216, 238, 261, 287, 314},
		attr.BaseDam: 245,
		attr.CDam:    []interface{}{490, 539, 592, 651, 715, 784, 862, 945},
		attr.HSpeed:  1.5,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Medium,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:     "Giant Skeleton",
		attr.Arena:    arena.Arena2,
		attr.Rarity:   rarity.Epic,
		attr.Type:     typ.Troop,
		attr.Desc:     `The bigger the skeleton, the bigger the bomb. Carries a bomb that blows up when the Giant Skeleton dies.`,
		attr.Elixir:   6,
		attr.BaseHP:   2000,
		attr.DPS:      []interface{}{86, 95, 104, 114, 126, 138, 152, 166},
		attr.BaseDam:  130,
		attr.BaseDDam: 720, // NOTE: Not shown in game anymore
		attr.HSpeed:   1.5,
		attr.Targets:  targets.Ground,
		attr.Speed:    speed.Medium,
		attr.Range:    rng.Melee,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:     "Balloon",
		attr.Arena:    arena.Arena2,
		attr.Rarity:   rarity.Epic,
		attr.Type:     typ.Troop,
		attr.Desc:     `As pretty as they are, you won't want a parade of THESE balloons showing up on the horizon. Drops powerful bombs and when shot down, crashes dealing area damage.`,
		attr.Elixir:   5,
		attr.BaseHP:   1050,
		attr.DPS:      []interface{}{200, 220, 242, 266, 292, 320, 352, 386},
		attr.BaseDam:  600,
		attr.BaseDDam: 205, // NOTE: Not shown in game anymore
		attr.HSpeed:   3,
		attr.Targets:  targets.Buildings,
		attr.Speed:    speed.Medium,
		attr.Range:    rng.Melee,
		attr.DTime:    1,
	}.init(),
	card{
		attr.Name:    "P.E.K.K.A",
		attr.Arena:   arena.Arena4,
		attr.Rarity:  rarity.Epic,
		attr.Type:    typ.Troop,
		attr.Desc:    `A heavily armored, slow melee fighter. Swings from the hip but packs a huge punch.`,
		attr.Elixir:  7,
		attr.BaseHP:  2600,
		attr.DPS:     []interface{}{283, 311, 342, 376, 413, 453, 498, 546},
		attr.BaseDam: 510,
		attr.HSpeed:  1.8,
		attr.Targets: targets.Ground,
		attr.Speed:   speed.Slow,
		attr.Range:   rng.Melee,
		attr.DTime:   1,
	}.init(),
	card{
		attr.Name:      "Golem",
		attr.Arena:     arena.Arena6,
		attr.Rarity:    rarity.Epic,
		attr.Type:      typ.Troop,
		attr.Desc:      `Slow but durable, only attacks buildings. When destroyed, explosively splits into two Golemites and deals area damage!`,
		attr.Elixir:    8,
		attr.BaseHP:    3200,
		attr.DPS:       []interface{}{78, 85, 94, 103, 113, 124, 137, 150},
		attr.BaseDam:   195,
		attr.BaseDDam:  195,
		attr.BaseGolLV: 1,
		attr.HSpeed:    2.5,
		attr.Targets:   targets.Buildings,
		attr.Speed:     speed.Slow,
		attr.Range:     rng.Melee,
		attr.DTime:     3,
	}.init(),
	card{
		attr.Name:     "Golemite",
		attr.From:     Golem,
		attr.Arena:    arena.Arena6,
		attr.Rarity:   rarity.Epic,
		attr.Type:     typ.Troop,
		attr.Desc:     ``,
		attr.Elixir:   0,
		attr.BaseHP:   650,
		attr.BaseDam:  40,
		attr.BaseDDam: 40,
		attr.HSpeed:   2.5,
		attr.Targets:  targets.Buildings,
		attr.Speed:    speed.Slow,
	}.init(),

	// --- Common Buildings ---
	card{
		attr.Name:    "Cannon",
		attr.Arena:   arena.Arena3,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Building,
		attr.Desc:    `Defensive building. Shoots cannonballs with deadly effect, but cannot target flying troops.`,
		attr.Elixir:  3,
		attr.BaseHP:  350,
		attr.DPS:     []interface{}{75, 82, 90, 98, 108, 120, 131, 143, 158, 173, 191, 210, 231},
		attr.BaseDam: 60,
		attr.HSpeed:  0.8,
		attr.Targets: targets.Ground,
		attr.Range:   5.5,
		attr.DTime:   1,
		attr.LTime:   30,
	}.init(),
	card{
		attr.Name:    "Tesla",
		attr.Arena:   arena.Arena4,
		attr.Rarity:  rarity.Common,
		attr.Type:    typ.Building,
		attr.Desc:    `Defensive building. Whenever it's not zapping the enemy, the power of Electrickery is best kept grounded.`,
		attr.Elixir:  4,
		attr.BaseHP:  450,
		attr.DPS:     []interface{}{80, 87, 96, 106, 116, 127, 140, 153, 168, 186, 203, 223, 246},
		attr.BaseDam: 64,
		attr.HSpeed:  0.8,
		attr.Targets: targets.AirAndGround,
		attr.Range:   5.5,
		attr.DTime:   1,
		attr.LTime:   40,
	}.init(),
	card{
		attr.Name:     "Mortar",
		attr.Arena:    arena.Arena6,
		attr.Rarity:   rarity.Common,
		attr.Type:     typ.Building,
		attr.Desc:     `Defensive building with a long range. Shoots exploding boulders that deal area damage. Cannot shoot at targets that get very close!`,
		attr.Elixir:   4,
		attr.BaseHP:   600,
		attr.DPS:      []interface{}{21, 23, 26, 29, 31, 34, 38, 41, 45, 50, 55, 60, 66},
		attr.BaseADam: 108,
		attr.HSpeed:   5,
		attr.Targets:  targets.Ground,
		attr.Range:    11.5,
		attr.DTime:    4,
		attr.LTime:    30,
	}.init(),

	// --- Rare Buildings ---
	card{
		attr.Name:      "Goblin Hut",
		attr.Arena:     arena.Arena1,
		attr.Rarity:    rarity.Rare,
		attr.Type:      typ.Building,
		attr.Desc:      `Building that spawns Spear Goblins. But don't look inside. You don't want to see how they are made.`,
		attr.Elixir:    5,
		attr.BaseHP:    735,
		attr.BaseSgoLV: 3,
		attr.SSpeed:    4.9,
		attr.DTime:     1,
		attr.LTime:     60,
	}.init(),
	card{
		attr.Name:     "Bomb Tower",
		attr.Arena:    arena.Arena2,
		attr.Rarity:   rarity.Rare,
		attr.Type:     typ.Building,
		attr.Desc:     `Defensive building that houses a Bomber. Deals area damage to anything dumb enough to stand near it.`,
		attr.Elixir:   5,
		attr.BaseHP:   950,
		attr.DPS:      []interface{}{62, 68, 75, 83, 91, 100, 110, 120, 132, 145, 160},
		attr.BaseADam: 100,
		attr.HSpeed:   1.6,
		attr.Targets:  targets.Ground,
		attr.Range:    6,
		attr.DTime:    1,
		attr.LTime:    40,
	}.init(),
	card{
		attr.Name:      "Tombstone",
		attr.Arena:     arena.Arena2,
		attr.Rarity:    rarity.Rare,
		attr.Type:      typ.Building,
		attr.Desc:      `Troop building that periodically deploys Skeletons to fight the enemy. When destroyed, spawns 4 Skeletons. Creepy!`,
		attr.Elixir:    3,
		attr.BaseHP:    240,
		attr.BaseSkeLV: 3,
		attr.SSpeed:    2.9,
		attr.DTime:     1,
		attr.LTime:     40,
	}.init(),
	card{
		attr.Name:      "Barbarian Hut",
		attr.Arena:     arena.Arena3,
		attr.Rarity:    rarity.Rare,
		attr.Type:      typ.Building,
		attr.Desc:      `Troop building that periodically deploys Barbarians to fight the enemy. Time to make the Barbarians.`,
		attr.Elixir:    7,
		attr.BaseHP:    1100,
		attr.BaseBarLV: 3,
		attr.SSpeed:    14,
		attr.DTime:     1,
		attr.LTime:     60,
	}.init(),
	card{
		attr.Name:     "Inferno Tower",
		attr.Arena:    arena.Arena4,
		attr.Rarity:   rarity.Rare,
		attr.Type:     typ.Building,
		attr.Desc:     `Defensive building, roasts targets for damage that increases over time. Burns through even the biggest and toughest enemies!`,
		attr.Elixir:   5,
		attr.BaseHP:   800,
		attr.DPSL:     []interface{}{50, 55, 60, 65, 72, 80, 87, 95, 105, 115, 127},
		attr.DPSH:     []interface{}{1000, 1100, 1210, 1330, 1460, 1600, 1760, 1930, 2120, 2330, 2560},
		attr.BaseDamL: 20,
		attr.BaseDamH: 400,
		attr.HSpeed:   0.4,
		attr.Targets:  targets.AirAndGround,
		attr.Range:    6,
		attr.DTime:    1,
		attr.LTime:    40,
	}.init(),
	card{
		attr.Name:   "Elixir Collector",
		attr.Arena:  arena.Arena6,
		attr.Rarity: rarity.Rare,
		attr.Type:   typ.Building,
		attr.Desc:   `You gotta spend Elixir to make Elixir.`,
		attr.Elixir: 6,
		attr.BaseHP: 580,
		attr.PSpeed: 8.5,
		attr.DTime:  1,
		attr.LTime:  70,
	}.init(),

	// --- Epic Buildings ---
	card{
		attr.Name:    "X-Bow",
		attr.Arena:   arena.Arena3,
		attr.Rarity:  rarity.Epic,
		attr.Type:    typ.Building,
		attr.Desc:    `Nice tower you got there. Would be a shame if this X-Bow whittled it down from this side of the Arena...`,
		attr.Elixir:  6,
		attr.BaseHP:  1000,
		attr.DPS:     []interface{}{80, 88, 96, 104, 116, 128, 140, 152},
		attr.BaseDam: 20,
		attr.HSpeed:  0.25,
		attr.Targets: targets.Ground,
		attr.Range:   11.5,
		attr.DTime:   4,
		attr.LTime:   40,
	}.init(),

	// --- Common Spells ---
	card{
		attr.Name:     "Arrows",
		attr.Arena:    arena.Arena0,
		attr.Rarity:   rarity.Common,
		attr.Type:     typ.Spell,
		attr.Desc:     `Arrows pepper a large area, damaging all enermies hit. Reduced damage to Crown Towers.`,
		attr.Elixir:   3,
		attr.BaseADam: 115,
		attr.CTDam:    []interface{}{46, 51, 56, 61, 67, 74, 81, 89, 98, 107, 118, 130, 142},
		attr.Radius:   4,
	}.init(),
	card{
		attr.Name:     "Zap",
		attr.Arena:    arena.Arena5,
		attr.Rarity:   rarity.Common,
		attr.Type:     typ.Spell,
		attr.Desc:     `Zaps enemies, briefly stunning them and dealing damage inside a small radius. Reduced damage to Crown Towers.`,
		attr.Elixir:   2,
		attr.BaseADam: 75,
		attr.CTDam:    []interface{}{30, 33, 36, 40, 44, 48, 53, 58, 64, 70, 77, 84, 93},
		attr.SDurF:    0.5,
		attr.Radius:   2.5,
	}.init(),

	// --- Rare Spells ---
	card{
		attr.Name:     "Fireball",
		attr.Arena:    arena.Arena0,
		attr.Rarity:   rarity.Rare,
		attr.Type:     typ.Spell,
		attr.Desc:     `Annnnnd... Fireball. Incinerates a small area, dealing high damage. Reduced damage to Crown Towers.`,
		attr.Elixir:   4,
		attr.BaseADam: 325,
		attr.CTDam:    []interface{}{130, 143, 158, 173, 190, 208, 229, 251, 276, 303, 333},
		attr.Radius:   2.5,
	}.init(),
	card{
		attr.Name:     "Rocket",
		attr.Arena:    arena.Arena3,
		attr.Rarity:   rarity.Rare,
		attr.Type:     typ.Spell,
		attr.Desc:     `Deals high damage to a small area. Looks really awesome doing it. Reduced damage to Crown Towers.`,
		attr.Elixir:   6,
		attr.BaseADam: 700,
		attr.CTDam:    []interface{}{280, 308, 339, 373, 409, 448, 493, 541, 594, 653, 717},
		attr.Radius:   2,
	}.init(),

	// --- Epic Spells ---
	card{
		attr.Name:    "Lightning",
		attr.Arena:   arena.Arena1,
		attr.Rarity:  rarity.Epic,
		attr.Type:    typ.Spell,
		attr.Desc:    `Bolts of lightning damage and stun up to three enemy troops or buildings with the most hitpoints in the target area. Reduced damage to Crown Towers.`,
		attr.Elixir:  6,
		attr.Count:   3,
		attr.BaseDam: 650,
		attr.CTDam:   []interface{}{260, 286, 315, 346, 380, 416, 458, 502},
		attr.SDurF:   0.5,
		attr.Radius:  3.5,
	}.init(),
	card{
		attr.Name:      "Goblin Barrel",
		attr.Arena:     arena.Arena1,
		attr.Rarity:    rarity.Epic,
		attr.Type:      typ.Spell,
		attr.Desc:      `Spawns three Goblins anywhere in the Arena. It's going to be a thrilling ride, boys!`,
		attr.Elixir:    3,
		attr.Radius:    1.5,
		attr.BaseGobLV: 6,
		attr.GobCount:  3,
	}.init(),
	card{
		attr.Name:     "Rage",
		attr.Arena:    arena.Arena3,
		attr.Rarity:   rarity.Epic,
		attr.Type:     typ.Spell,
		attr.Desc:     `Increases troop movement and attack speed. Buildings attack faster and summon troops quicker, too. Chaaaarge!`,
		attr.Elixir:   2,
		attr.BaseDurU: attr.BaseDuration{BaseValue: 6, Increment: 0.5},
		attr.Boost:    35,
		attr.Radius:   5,
	}.init(),
	card{
		attr.Name:      "Freeze",
		attr.Arena:     arena.Arena4,
		attr.Rarity:    rarity.Epic,
		attr.Type:      typ.Spell,
		attr.Desc:      `Freezes troops and buildings, making them unable to move or attack. Everybody chill.`,
		attr.Elixir:    4,
		attr.BaseFDurU: attr.BaseDuration{BaseValue: 4, Increment: 0.3},
		attr.Radius:    3,
	}.init(),
	card{
		attr.Name:     "Mirror",
		attr.Arena:    arena.Arena5,
		attr.Rarity:   rarity.Epic,
		attr.Type:     typ.Spell,
		attr.Desc:     `Mirrors your last card played for +1 Elixir.`,
		attr.Elixir:   common.X,
		attr.BaseMCLV: 7,
		attr.BaseMRLV: 5,
		attr.BaseMELV: 2,
		attr.MLLV:     []interface{}{1, 1, 1, 2, 3, 4, 5, 6},
	}.init(),
}
